### ISSUE TITLE
Makefile to build for MacOS and Linux

### ISSUE THREAD

**Issue by joycemacksuele** [Janeway42/webserv#6]
* On the Makefile (Need to test and search a bit more to implement in a good way but I have done it on one of my cpp projects too):
``` shell
linux_build: CPPFLAGS +=  -DLINUX_BUILD=1# see if ON/OFF also works

# or maybe (did not try at all this one)
!IF DEFINED( LINUX_BUILD )
CPPFLAGS +=  -DLINUX_BUILD=1# see if ON/OFF also works
!ENDIF

```
[About Makefile preprocessing operators](https://learn.microsoft.com/en-us/cpp/build/reference/makefile-preprocessing?view=msvc-170)

* To build the program:
``` shell
$ make # for Mac (standard for us)
# or
$ make linux_build
```

* To set on a header file:
``` c++
// A function to check the macro so we don't have weird macros ifdef on the code (it would not be aligned too)
constexpr bool linux_build(void) {
    #ifdef LINUX_BUILD
        return true;
    #else
        return false;
    #endif
}
```

* To use throughout the code:
``` c++
class, function, etc... {
    if (target_is_linux()) {
        // do whatever wanted!!!
    }
}
```

**Comment by jaka72** [comment]
I did Linux/Mac Makefile for Cub3D,
But we are using kQueue which is not working on Linux, so maybe it is unnecessary
